spring:
  profiles:
    active: dev

  zrrpc:
    server:
      - name: demo-server
        domain:
          - 127.0.0.1:9999
        classes:
          - com.zr.zrrpc.server.inter.IUserService
          - com.zr.zrrpc.server.inter.IAccountService
